version: "3.8"
services:
  app:
    build: .
    container_name: "item-container"
    ports:
      - 8181:8181
    depends_on:
      - mongodb
      
  mongodb:
    image: mongo:latest
    container_name: "mongodb-container"
    ports:
      - 27070:27017